spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL}/${MYSQL_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true